### ISSUE TITLE
Use it with ros2 foxy and with python

### ISSUE THREAD

**Issue by alvaropascuaI** [ros-sports/ros_image_to_qimage#2] opened 2022-05-09 11:20 UTC
Hello, I am implementing ros_image_to_qimage with the versions of ros2 foxy and in the python language but I don't know how to import it or how to use it in python

**Comment by ijnek** [comment] 2022-05-09 12:52
I'm sorry to inform you that the library is implemented in cpp, and can only be used in cpp projects.

I can perhaps give you some tips on implementing this in Python. This package converts ros images -> cv images -> qimage. You'd want to do something similar.

What I'd recommend, is to look at how this package does the conversion in [ros_image_to_qimage.cpp](https://github.com/ros-sports/ros_image_to_qimage/blob/rolling/src/ros_image_to_qimage.cpp) and try and reproduce it in python. 

``cv_bridge`` has a method [``imgmsg_to_cv2``](https://github.com/ros-perception/vision_opencv/blob/0b69de38953f21090ac62bc90eb700e8bc98a023/cv_bridge/python/cv_bridge/core.py#L147) which you can do to perform the conversion from ros -> cv.

Although I'm going to close this issue off since it's more of a question, feel free to keep commenting on it.

**Closed as completed** 2022-05-09 12:56 UTC

**Comment by ijnek** [comment] 2022-06-18 07:37
@alvaropascuaI An update on this topic, 

## The python api has been added.

The new changes are only available on Rolling, and will be included in upcoming releases, but won't be backported to previous distros (like Humble, Galactic, Foxy).
